apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecc-openlxp-xss
spec:
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
      - name: code-il2-pull-creds
      containers:
      - name: ecc-openlxp-xss
        image: ecc/ecc-openlxp-xss
        volumeMounts:
          - mountPath: "/tmp/shared/"
            name: xss-storage-mount
        command:
        - "/bin/sh"
        - "-exc"
        - |
          sed -i 's/hashlib.md5()/hashlib.md5(usedforsecurity=False)/g' /tmp/app/.cache/python-packages/django/db/backends/utils.py
          ../start-app.sh
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-vars
        - secretRef:
            name: mysql-connect-info
        - secretRef:
            name: xds-secrets
        - configMapRef:
            name: cluster-prefix
        env:
        - name: LOG_PATH
          value: "/tmp/debug.log"
        - name: FORCE_SCRIPT_NAME
          value: "/ecc-openlxp-xss"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-connect-info
              key: MYSQL_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_NAME_7
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_ADMIN_USER_7
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_ADMIN_PASSWORD_7
        - name: MYSQL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_NAME_7
        - name: MYSQL_DB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_ADMIN_USER_7
        - name: MYSQL_DB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_ADMIN_PASSWORD_7
        - name: MYSQL_DB_RW_USER
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_RW_USER_7
        - name: MYSQL_DB_RW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_RW_PASSWORD_7
        - name: MYSQL_DB_RO_USER
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_RO_USER_7
        - name: MYSQL_DB_RO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: MYSQL_DB_RO_PASSWORD_7
      - name: xss-nginx
        image: nginx/nginx
        ports: 
          - containerPort: 8080
            name: xss-nginx-port
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: xss-storage-mount
          - mountPath: /etc/nginx/conf.d/
            name: nginx-default
      volumes:
        - name: xss-storage-mount
          persistentVolumeClaim:
            claimName: xss-storage-claim
        - name: nginx-default
          configMap:
            name: xss-nginx-default-config

