# Generated by Django 3.2.13 on 2022-05-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220309_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementalledger',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
