# Generated by Django 3.2.13 on 2022-05-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_supplementalledger_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositeledger',
            name='metadata_transmission_status',
            field=models.CharField(blank=True, choices=[('Successful', 'S'), ('Failed', 'F'), ('Pending', 'P'), ('Ready', 'R'), ('Cancelled', 'C')], default='Ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='compositeledger',
            name='metadata_transmission_status_neo4j',
            field=models.CharField(blank=True, choices=[('Successful', 'S'), ('Failed', 'F'), ('Pending', 'P'), ('Ready', 'R'), ('Cancelled', 'C')], default='Ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='metadataledger',
            name='composite_ledger_transmission_status',
            field=models.CharField(blank=True, choices=[('Successful', 'S'), ('Failed', 'F'), ('Pending', 'P'), ('Ready', 'R'), ('Cancelled', 'C')], default='Ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplementalledger',
            name='composite_ledger_transmission_status',
            field=models.CharField(blank=True, choices=[('Successful', 'S'), ('Failed', 'F'), ('Pending', 'P'), ('Ready', 'R'), ('Cancelled', 'C')], default='Ready', max_length=10),
        ),
    ]
