# Generated by Django 3.2.13 on 2022-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220601_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataledger',
            name='unique_record_identifier',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplementalledger',
            name='unique_record_identifier',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
