# Generated by Django 3.2.13 on 2022-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220607_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neo4jConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo4j_uri', models.CharField(help_text='Enter the host uri for the Neo4j (Graph Database) to use.', max_length=200)),
                ('neo4j_user', models.CharField(help_text='Enter the user ID to connect with Neo4j', max_length=200)),
                ('neo4j_pwd', models.CharField(help_text='Enter the user ID to connect with Neo4j', max_length=200)),
            ],
        ),
    ]
