# Generated by Django 3.2.14 on 2022-07-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_neo4jconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Enter the field path', max_length=255)),
                ('operation', models.CharField(choices=[('INCLUDE', 'Include'), ('EXCLUDE', 'Exclude')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FilterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Enter the field path', max_length=255)),
                ('comparator', models.CharField(choices=[('EQUAL', 'Equal'), ('UNEQUAL', 'Not Equal'), ('CONTAINS', 'Contains')], max_length=200)),
                ('field_value', models.CharField(help_text='Enter the field value', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='XISDownstream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xis_api_endpoint', models.URLField(help_text='Enter the XIS Instance API endpoint')),
                ('xis_api_endpoint_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=200)),
                ('composite_experiences', models.ManyToManyField(blank=True, related_name='xis_destination', to='core.CompositeLedger')),
                ('filter_metadata', models.ManyToManyField(blank=True, related_name='xis_downstream', to='core.FilterMetadata')),
                ('filter_records', models.ManyToManyField(blank=True, related_name='xis_downstream', to='core.FilterRecord')),
            ],
        ),
        migrations.CreateModel(
            name='XISUpstream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xis_api_endpoint', models.URLField(help_text='Enter the XIS Instance API endpoint')),
                ('xis_api_endpoint_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=200)),
                ('metadata_experiences', models.ManyToManyField(blank=True, related_name='xis_source', to='core.MetadataLedger')),
                ('supplemental_experiences', models.ManyToManyField(blank=True, related_name='xis_source', to='core.SupplementalLedger')),
            ],
        ),
        migrations.DeleteModel(
            name='XISSyndication',
        ),
    ]
