# Generated by Django 3.2.14 on 2022-07-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220707_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='xisdownstream',
            name='source_name',
            field=models.CharField(default='www.example.com', help_text='Enter the name to send data as', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compositeledger',
            name='updated_by',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='filterrecord',
            name='field_value',
            field=models.CharField(blank=True, help_text='Enter the field value', max_length=255),
        ),
        migrations.AlterField(
            model_name='metadataledger',
            name='updated_by',
            field=models.CharField(blank=True, default='System', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplementalledger',
            name='updated_by',
            field=models.CharField(blank=True, default='System', max_length=10),
        ),
    ]
