# Generated by Django 3.2.20 on 2023-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230628_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xisdownstream',
            name='xis_api_key',
            field=models.CharField(help_text='Enter the XIS API Key', max_length=128),
        ),
    ]
