apiVersion: v1
kind: Service
metadata:
  name: ecc-openlxp-xis
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: redis-xis
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
