apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  authentication: istio-auth

resources:
- ecc-openlxp-xds

patches:
- path: patches/deployment-defaults.yaml
  target:
    kind: Deployment
- path: patches/deployment-defaults.yaml
  target:
    kind: StatefulSet
