apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: ecc-openlxp-xia-moodle
  authentication: istio-auth

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
- name: xia-moodle-nginx-default-config
  files:
  - nginx.conf