kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   labels:
      app: ecc-openlxp-xds
   name: xds-storage-claim
spec:
   accessModes:
      - "ReadWriteOnce"
   resources:
      requests:
         storage: "1Gi"
