# Generated by Django 3.2.25 on 2024-06-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsrconfiguration',
            name='token',
            field=models.CharField(default='token1', help_text='Enter the XSR API endpoint', max_length=200),
            preserve_default=False,
        ),
    ]
