kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   labels:
      app: ecc-openlxp-xia-edx
   name: xia-edx-storage-claim
spec:
   accessModes:
      - "ReadWriteOnce"
   resources:
      requests:
         storage: "1Gi"
