apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: defaults
spec:
  revisionHistoryLimit: 1
  template:
    spec:
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
      - name: code-il2-pull-creds
