"""
Django settings for openlxp_xia_moodle project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import mimetypes
import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY_VAL')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

mimetypes.add_type("text/css", ".css", True)

ALLOWED_HOSTS = os.environ.get('HOSTS').split(';')

SELF_VALUE = "'self'"  # defining a constant
IMG_DATA_VALUE = "data:"

CSP_DEFAULT_SRC = (SELF_VALUE, "https://ecc.staging.dso.mil/")
CSP_SCRIPT_SRC = (SELF_VALUE,)
CSP_IMG_SRC = (SELF_VALUE, IMG_DATA_VALUE)
CSP_STYLE_SRC = ("https://ecc.staging.dso.mil/")
CSP_FRAME_SRC = (SELF_VALUE,)
CSP_FONT_SRC = (SELF_VALUE,)


# Application definition

INSTALLED_APPS = [
    "admin_interface",
    "colorfield",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'p1_auth',
    'openlxp_xia',
    'openlxp_P1_notification',
    'django_celery_beat',
    'django_celery_results',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'p1_auth.middleware.AuthenticateSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'openlxp_P1_notification.middleware.TemplateMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if os.environ.get('TESTING') is None or \
        os.environ.get('TESTING') != 'true':
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = True

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True


ROOT_URLCONF = 'openlxp_xia_moodle_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'openlxp_xia_moodle_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': 3306,
        'OPTIONS': {
                    'charset': 'utf8mb4',
                }
            },
}

DEFAULT_AUTO_FIELD='django.db.models.AutoField'

AUTHENTICATION_BACKENDS = (
    "p1_auth.backends.PlatformOneAuthentication",
    "django.contrib.auth.backends.ModelBackend",
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "p1_auth.backends.PlatformOneRestAuthentication",
    ],

    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

EMAIL_BACKEND = 'django_ses.SESBackend'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'

if os.environ.get('FORCE_SCRIPT_NAME') is not None:
    FORCE_SCRIPT_NAME = os.environ.get('FORCE_SCRIPT_NAME')

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

CELERY_BROKER_URL = "redis://redis:6379"
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}

LOG_PATH = os.environ.get('LOG_PATH')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'loggers': {
        'dict_config_logger': {
            'handlers': ['console', 'file_logs'],
            'level': 'INFO',
            'propagate': True,
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'simpleRe',
        },
        'file_logs': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': LOG_PATH,
            'formatter': 'simpleRe',
        },

    },

    'formatters': {
        'simpleRe': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        }
    }
}

# Directory to store files during upload scanning

if os.environ.get('TMP_SOURCE_DIR') is not None and\
        len(os.environ.get('TMP_SOURCE_DIR')) > 0:
    TMP_SOURCE_DIR = os.environ.get('TMP_SOURCE_DIR')
else:
    TMP_SOURCE_DIR = os.path.join(BASE_DIR, 'tmp', 'source')
TMP_SOURCE_DIR = os.path.join(TMP_SOURCE_DIR, '')

# P1-AUTH SETTINGS

USER_ATTRIBUTES_MAP = {
    'last_name': 'family_name',
    'first_name': 'given_name',
    'email': 'email'
}

USER_MEMBERSHIPS = {
    'groups': {
        'name': 'group-simple'
    },
}

if os.environ.get('STAFF_FLAG') is not None:
    USER_STAFF_FLAG = os.environ.get('STAFF_FLAG')

if os.environ.get('STAFF_VALUE') is not None:
    USER_STAFF_VALUE = os.environ.get('STAFF_VALUE')

if os.environ.get('SU_FLAG') is not None:
    USER_SUPERUSER_FLAG = os.environ.get('SU_FLAG')

if os.environ.get('SU_VALUE') is not None:
    USER_SUPERUSER_VALUE = os.environ.get('SU_VALUE')

if os.environ.get('REQUIRE_JWT') is not None:
    REQUIRE_JWT = True
