apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecc-openlxp-xia-jobs
spec:
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
        - name: code-il2-pull-creds
      containers:
        - name: ecc-openlxp-xia-jobs
          image: ecc/ecc-openlxp-xia-jobs
          volumeMounts:
          - mountPath: "/tmp/shared/"
            name: xia-jobs-storage-mount
          command:
          - "/bin/sh"
          - "-exc"
          - |
            sed -i 's/hashlib.md5()/hashlib.md5(usedforsecurity=False)/g' /tmp/app/.cache/python-packages/django/db/backends/utils.py
            ../start-app.sh
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: mysql-connect-info
          - secretRef:
              name: mysql-db-credentials
          - configMapRef:
              name: app-vars
          - configMapRef:
                name: cluster-prefix
          - secretRef:
              name: xia-jobs-secrets
          - secretRef:
              name: p1ps-secrets
          env:
          - name: HOSTS
            value: "ecc.staging.dso.mil"
          - name: FORCE_SCRIPT_NAME
            value: "/ecc-openlxp-xia-jobs"
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name:  mysql-connect-info 
                key: MYSQL_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-db-credentials
                key: MYSQL_DB_NAME_10
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-db-credentials
                key: MYSQL_DB_ADMIN_USER_10
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-credentials
                key: MYSQL_DB_ADMIN_PASSWORD_10
          - name: MYSQL_DB_RW_USER
            valueFrom:
              secretKeyRef:
                name: mysql-db-credentials
                key: MYSQL_DB_RW_USER_10
          - name: MYSQL_DB_RW_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-credentials
                key: MYSQL_DB_RW_PASSWORD_10
          - name: MYSQL_DB_RO_USER
            valueFrom:
              secretKeyRef:
                name: mysql-db-credentials
                key: MYSQL_DB_RO_USER_10
          - name: MYSQL_DB_RO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-credentials
                key: MYSQL_DB_RO_PASSWORD_10
          - name: P1PS_BASE_URL
            valueFrom:
              secretKeyRef:
                name: p1ps-secrets
                key: P1PS_BASE_URL
          - name: P1PS_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: p1ps-secrets
                key: P1PS_AUTH_TOKEN
          - name: P1PS_TEAM_ID
            valueFrom:
              secretKeyRef:
                name: p1ps-secrets
                key: P1PS_TEAM_ID
        - name: xia-jobs-nginx
          image: nginx/nginx
          ports: 
            - containerPort: 8080
              name: moodle-ngnx-prt
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: xia-jobs-storage-mount
            - mountPath: /etc/nginx/conf.d/
              name: nginx-default
      volumes:
        - name: xia-jobs-storage-mount
          persistentVolumeClaim:
            claimName: xia-jobs-storage-claim
        - name: nginx-default
          configMap:
            name: xia-jobs-nginx-default-config